# Generated by Django 6.0.3 on 2026-10-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_academic_periods'),
        ('students', '0003_require_student_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('admitted', 'Admitted'), ('promoted', 'Promoted'), ('transferred', 'Transferred'), ('graduated', 'Graduated'), ('deactivated', 'Deactivated')], max_length=20)),
                ('from_class', models.CharField(blank=True, max_length=50)),
                ('from_section', models.CharField(blank=True, max_length=10)),
                ('to_class', models.CharField(blank=True, max_length=50)),
                ('to_section', models.CharField(blank=True, max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_history', to='accounts.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_history', to='accounts.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_history', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_history', to='accounts.term')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
    ]
