# Generated by Django 6.0.3 on 2026-10-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role_academicyear_auditlog_guardian_and_more'),
        ('finance', '0004_invoice_void_reason_invoice_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='accounts.term'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.term'),
        ),
    ]
