# Generated by Django 6.0.3 on 2026-10-03 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options'),
        ('courses', '0003_require_course_school'),
        ('students', '0003_require_student_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='accounts.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'student'), name='unique_student_course_enrollment')],
            },
        ),
    ]
