# Generated by Django 6.0.3 on 2026-10-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_academic_periods_and_audit_guardian'),
        ('courses', '0004_create_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments', to='accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments', to='accounts.term'),
        ),
    ]
