# Generated by Django 6.0.3 on 2026-10-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_academic_periods_and_audit_guardian'),
        ('attendance', '0001_initial_attendance_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='accounts.term'),
        ),
    ]
